language: ruby
rvm:
  - 2.1.1
install:
  - bundle install
script:
  - bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: AKIAJWL6V6CFRNIQHJ4A
  secret_access_key:
    secure: PLUzDoX2GjYnrXp49F5cOAOVtjO2w7HQoeqtxGm1oSOthFlmFKqHweABXEXlO6ABhJzdsv4kYEyC0w/g3tHgtKOgIxL13jaKiuYt3SVIAUFE9NfhPPP4LTwFT9JuHrnPC8e5M9Do47zvgnqw2GESEc4Orbf8wEBsVzvTOVNR3ks=
  bucket: text.ykhs.org
  region: ap-northeast-1
  endpoint: s3-ap-northeast-1.amazonaws.com
  local-dir: _deploy
  skip_cleanup: true
  on:
    repo: ykhs/text.ykhs.org
